### ISSUE TITLE
Run via docker doesn't work?

### ISSUE THREAD

**Issue by bblodfon** [biohackrxiv/bhxiv-gen-pdf#13]
I run the two commands as specified [here](https://github.com/biohackrxiv/bhxiv-gen-pdf#run-via-docker) after cloning the repo, and I got back:

```
Unknown option --citeproc.
Try pandoc --help for more information.
Failed to generate paper.pdf!
```

My pandoc includes it though (I think!):
```
pandoc --version
pandoc 2.12
Compiled with pandoc-types 1.22, texmath 0.12.1.1, skylighting 0.10.4,
citeproc 0.3.0.8, ipynb 0.1.0.1
```

Any idea what might be causing this?

**Comment by inutano** [comment]
You meant the two commands below, right?

```
$ docker build -t biohackrxiv/gen-pdf:local -f docker/Dockerfile .
$ docker run --rm -it -v $(pwd):/work -w /work biohackrxiv/gen-pdf:local gen-pdf /work/example/logic
```

This will use the Dockerfile [here](https://github.com/biohackrxiv/bhxiv-gen-pdf/blob/master/docker/Dockerfile) and it specifies to install the pandoc 2.2, though it's a bit old one. Your local pandoc version is not relevant since the process will be completed inside the container.

If you don't edit the Dockerfile, correctly build the image, and run it, you should get this:

```
$ docker run --rm -it -v $(pwd):/work -w /work biohackrxiv/gen-pdf:local pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
Default user data directory: /root/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

I've confirmed that I successfully built the container and run the command without error. Could you provide the commands you actually typed?

**Comment by bblodfon** [comment]
Hi @inutano , thanks for looking at this. I've run exactly the two commands you provided. I did so today as well. Removed all docker images associated with the `biohackrxiv/gen-pdf` and recreated a new image from scratch. The `docker run` command resulted in the same error as I displayed in the first message (`Unknown option --citeproc.`). I ran the other command as well and got the same thing: 

```
john:~$ docker run --rm -it -v $(pwd):/work -w /work biohackrxiv/gen-pdf:local pandoc --version
pandoc 2.2.1
Compiled with pandoc-types 1.17.5.1, texmath 0.11.1, skylighting 0.7.5
Default user data directory: /root/.pandoc
Copyright (C) 2006-2018 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by bblodfon** [comment]
Updated pandoc looks like this now:
```
docker run --rm -it -v $(pwd):/work -w /work biohackrxiv/gen-pdf:local pandoc --version
pandoc 2.16.1
Compiled with pandoc-types 1.22.1, texmath 0.12.3.2, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2
User data directory: /root/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
````

**Comment by bblodfon** [comment]
PR #17 solved this
