### ISSUE TITLE
Docker image issue: librsvg2-bin error

### ISSUE THREAD

**Issue by jedrzejkubica** [biohackrxiv/bhxiv-gen-pdf#31]
I was having an issue running docker/Dockerfile. I fixed it by replacing:

librsvg2-bin=2.50.3+dfsg-1

with:

librsvg2-bin=2.50.3+dfsg-1+deb11u1

**Comment by inutano** [comment]
@jjjk123 Correct, that was my easy mistake and will be fixed. Sorry for not replying earlier and thank you so much for letting us know! Be relaxed to send a PR next time please ;)
