### ISSUE TITLE
[Idea] publish the docker image to ghcr so it can be used to generate the pdf using Github Actions

### ISSUE THREAD

**Issue by burgerga** [biohackrxiv/bhxiv-gen-pdf#39]
The github container registry is free to use for public docker images, see instructions here: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images

People can then more easily build their papers, and even use this public docker image in a Github Action workflow to automatically build their paper on every commit.

**Comment by egonw** [comment]
Yeah, that would be awesome if we could get the template repository have an action that does that for all PRs to that repository and attached the PDF to the PR

**Comment by burgerga** [comment]
(Using it on PRs from public forks is slightly more complicated; see https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/)

**Comment by inutano** [comment]
Fantastic, thank you @burgerga !! I'm merging your PR now
